version: '3.8'
services:
  frontend:
    image: angular-tailwind-starter:dev
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    volumes:
      - ./src:/app/src
